name: Metrics

on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - v2

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          committer_branch: v2-dist
          token: ${{ secrets.GH_TOKEN }}

          # Options
          user: renbaoshuo
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          config_timezone: Asia/Shanghai
          config_twemoji: yes
          config_octicon: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, languages-graphs, os-graphs
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_languages_other: yes
          plugin_wakatime_languages_ignored: Other
